#!/bin/bash

apt install php -y
php -v
apt install php-apcu php-bcmath php-cli php-common php-curl php-gd php-gmp php-imagick php-intl php-mbstring php-mysql php-zip php-xml phpenmod bcmath gmp imagick intl -y
apt install unzip -y
apt install libmagickcore-6.q16-6-extra -y

wget https://download.nextcloud.com/server/releases/nextcloud-24.0.1.zip
unzip nextcloud-24.0.1.zip
chown -R www-data:www-data nextcloud
mv nextcloud /var/www/html
a2dissite 000-default.conf
echo 'The file: /etc/apache2/sites-available/nextcloud.conf will be populated.
echo
echo '<VirtualHost *:80>' > /etc/apache2/sites-available/nextcloud.conf
echo '    DocumentRoot "/var/www/html/nextcloud"' >> /etc/apache2/sites-available/nextcloud.conf
echo '    ServerName example.com' >> /etc/apache2/sites-available/nextcloud.conf
echo '' >> /etc/apache2/sites-available/nextcloud.conf
echo '    <Directory "/var/www/html/nextcloud/">' >> /etc/apache2/sites-available/nextcloud.conf
echo '        Options MultiViews FollowSymlinks' >> /etc/apache2/sites-available/nextcloud.conf
echo '        AllowOverride All' >> /etc/apache2/sites-available/nextcloud.conf
echo '        Order allow,deny' >> /etc/apache2/sites-available/nextcloud.conf
echo '        Allow from all' >> /etc/apache2/sites-available/nextcloud.conf
echo '    </Directory>' >> /etc/apache2/sites-available/nextcloud.conf
echo '' >> /etc/apache2/sites-available/nextcloud.conf
echo '    TransferLog /var/log/apache2/nextcloud_access.log' >> /etc/apache2/sites-available/nextcloud.conf
echo '    ErrorLog /var/log/apache2/nextcloud_error.log' >> /etc/apache2/sites-available/nextcloud.conf
echo '' >> /etc/apache2/sites-available/nextcloud.conf
echo '</VirtualHost>' >> /etc/apache2/sites-available/nextcloud.conf
echo '' >>/etc/apache2/sites-available/nextcloud.conf

