#!/.bin/bash

sudo apt update
sudo apt upgrade -y
sudo adduser os-dave -q
sudo usermod -aG root os-dave
echo
echo
echo "Installing Apache Webserver"
echo
apt install apache2 -y
#

echo
echo
echo "Configuring Firewall"
echo
# ufw status
ufw allow openssh
ufw allow in "Apache Full"
ufw enable
# ufw status
#

echo
echo
echo "Finishing up with Apache"
echo
a2dismod mpm_event
a2enmod mpm_prefork
#
systemctl restart apache2
#systemctl status apache2
#

echo
echo
echo "Installing MariaDB"
echo
apt install mariadb-server -y
systemctl status mariadb
systemctl enable mariadb
echo
echo
echo "Anser the following security questions thusly:
echo "1 DO create root password and log it somewhere"
echo "2 NO Switch socket authentication
ecbi "3 NO Change the root password"
echo "4 DO Remove anonymous users"
echo "5 DO Dissallow root login remotely?"
echo "3 Remove test database and access to it?"
echo "4 Reload privilege tables now?"
#
mysql_secure_installation
#

echo "## Enter the following into the database program"
echo "CREATE DATABASE nextcloud;"
echo "SHOW DATABASES;"
echo "GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'localhost' IDENTIFIED BY '1UbUnTu!UbUnTu';"
echo "FLUSH PRIVILEGES;"
echo "quit"
echo
sudo mysql -u root
#








